### ISSUE TITLE
Conceptual bug: Bad deviation calculation

### ISSUE THREAD

**Issue by mathieuboudreau** [agahkarakuzu/rrsg2020-dashboard#1]
This line: https://github.com/agahkarakuzu/rrsg2020-dashboard/blob/3c10f2b9add287651abcf3f12bd245a1f55f969c/apps/phantom.py#L634

doesn't accurately estimate the deviation of the measurements to the reference. You're normalizing it (denominator) by the mean between the reference and the measured value. You should instead normalize it by the reference value, as it is the NIST measurements and should be taken as the absolute reference. So instead, you should be calculating something like:

```python
t1 = list(np.abs(np.array(t1) - np.array(NIST_REF[version][metric]))/(p.array(NIST_REF[version][metric]))*100) 
```

**Comment by mathieuboudreau** [comment]
(within a parenthese close, I might be missing one)

**Comment by mathieuboudreau** [comment]
This line also has a bug (where you also forgot to divide by two like above, so the deviations are actually off by 2x relative to your previous definition):

https://github.com/agahkarakuzu/rrsg2020-dashboard/blob/3c10f2b9add287651abcf3f12bd245a1f55f969c/apps/phantom.py#L1153

**Comment by agahkarakuzu** [comment]
89001bb815426a16e63580eb299441a90b38fb4a
